### ISSUE TITLE
Feature Request - Informative Prior for Mixtures

### ISSUE THREAD

**Issue by krshedd** [eriqande/gsi_sim#1]
Hi Eric,
We have recently been looking into using `gsi_sim` for mixed stock analysis here at the ADF&G Gene Conservation Laboratory. Currently, we are still using `BAYES` as our standard program for MSA. As you are aware, `BAYES` is slow and cumbersome for large baselines or mixtures and doesn't allow batching runs. While we have tested various versions of DFO's re-write of `BAYES` in C++, `cBAYES`, it does not meet our needs as it does not allow for an informative prior for mixtures. Having looked through the --help-full and trying out the test_data, it appears that `gsi_sim` currently doesn't allow for an informative prior for mixtures. Do you have plans to include this feature in the future?
Cheers,
Kyle

**Comment by eriqande** [comment]
Hey Kyle,

Cook stuff. It wasn't hard to add that option to gsi_sim.  I've pushed the changes up in f8586ccedf6fce687c87e4630349bb27982da9a9.  The option is --bayes-pi-prior.   Unfortunately, I have only updated the Mac (Darwin) binary for that. But you can pull down the sources and compile them for whatever platform you want to use.

It is great to hear from you.  

As it turns out, I am totally rewriting gsi_sim to incorporate some new features:
1. Written in R/Rcpp
2. Unbiased estimation of reporting unit proportions.
3. Hierarchical correlated allele frequencies prior over populations and reporting units.

So, I am pretty thick in the weeds on that project. But it won't be done till the fall, so I figured I could update gsi_sim so y'all could use it.

Best regards,

eric
